### ISSUE TITLE
View Transition API を使った MPA でのページ間アニメーション

### ISSUE THREAD

**Issue by yaakaito** [yaakaito/yaakaito#9]
Chrome 126 で SPA でない通常のページ遷移の際にも間を補完するアニメーションを実装することが可能になりました。

- [New in Chrome 126  |  Blog  |  Chrome for Developers](https://developer.chrome.com/blog/new-in-chrome-126#cross-document-transitions)
- [View Transition API によるスムーズな遷移  |  View Transitions  |  Chrome for Developers](https://developer.chrome.com/docs/web-platform/view-transitions?hl=ja)

次の CSS を遷移元と遷移先で設定しておくことで、デフォルトではフェードイン・アウトなアニメーションが適用されるようになります。

```css
@view-transition {
  navigation: auto;
}
```

例としてナビゲーションにマーカーが付くようなページを用意しました。

- https://yaakaito.github.io/code-sandbox/mp-view-transition/index.html

これは CSS Anchor Positioning API を利用して実装していて、それぞれのページでは `position-anchor` にそのページのものを指定するだけでページ遷移時にアニメーションが適用されます。

- [CSS アンカー ポジショニング API のご紹介  |  Blog  |  Chrome for Developers](https://developer.chrome.com/blog/anchor-positioning-api?hl=ja)

```html
  <body>
    <nav>
        <ul>
            <li id="navHome">
                <a href="./index.html">🏠 Home</a>
            </li>
            <li id="navBlog">
                <a href="./blog.html">🖊 Blog</a>
            </li>
            <li id="navAbout">
                <a href="./about.html">🐴 About</a>
            </li>
        </ul>
    </nav>
    <div id="mark"></div>
  </body>
```

```css
@view-transition {
  navigation: auto;
}
#navHome {
  anchor-name: --anchor-home;
}
#navBlog {
  anchor-name: --anchor-blog;
}
#navAbout {
  anchor-name: --anchor-about;
}
#mark {
  position: absolute;
  position-anchor: --anchor-home;
  background: black;
  left: anchor(left);
  top: anchor(top);
  width: 4px;
  height: 32px;
  view-transition-name: mark;
}
```

```css
#mark {
    position-anchor: --anchor-home;
}
```
